version: 0.0
os: linux
files:
  - source: /templates
    destination: /var/www/html/
#hooks:
#  AfterInstall:
#    - location: scripts/install_dependencies
#      timeout: 1000
#      runas: root
#
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
